### ISSUE TITLE
prop type `label` is invalid

### ISSUE THREAD

**Issue by rafaelcapucho** [mohithg/react-switchery#1]
Hi,

Running the sample that you provide in the Readme, I got errors:

`Warning: Failed prop type: Switch: prop type `label` is invalid; it must be a function, usually from React.PropTypes.`

Providing **or not** a label prop, I get the same error,

```
<Switch
            className="switch-class"
            onChange={this.onChange}
            label="testando"
            options={
              {
                color: '#474F79',
                size: 'small'
              }
            }
            checked
          />
```

Thank you.

**Comment by rafaelcapucho** [comment]
Probably it couldn't be `label` here:

https://github.com/mohithg/react-switchery/blob/master/src/index.js#L74

**Comment by rafaelcapucho** [comment]
@mohithg Could you please propagate this changes in a new version of the package in the npm repo?

The 1.0 version is still giving errors.

https://www.npmjs.com/package/react-switchery

**Comment by mohithg** [comment]
@rafaelcapucho I made a new version 1.1.0. Thanks for letting me know.
