### ISSUE TITLE
option size is not working for me

### ISSUE THREAD

**Issue by andylacko** [mohithg/react-switchery#16]
```
            <Switch
              className="switchery-small"
              onChange={this.handleChange.bind(this)}
              options={
                {
                  color: '#474F79',
                  size: 'small'
                }
              }
              checked
            />
```

stays the same gigantic size

**Comment by mohithg** [comment]
@andylaci Thanks for using react-switchery. This happened for you because we used old version of switchery, updated it now in 7b2dd3bc1bd5e6cae7914e829b511d5f4432b0f6.
Please use our latest version and you will find this working.
