### ISSUE TITLE
Failed propType: Switch: prop type `label` is invalid & Switchery is not defined(…)

### ISSUE THREAD

**Issue by foreseaz** [mohithg/react-switchery#2]
Hi, I just tested the `react-switchery` with the example code and got the error as below:

```
warning.js:36Warning: Failed propType: Switch: prop type `label` is invalid; it must be a function, usually from React.PropTypes. Check the render method of `SwitcherySwitch`.
index.js:56Uncaught ReferenceError: Switchery is not defined(…)
```

**Comment by mohithg** [comment]
@foreseaz Thanks for using and testing my repo. Fixed the issue that you mentioned. Kindly check the latest version.

**Comment by dusterio** [comment]
Doesn't seem to be fixed actually, it's still the same issue

**Comment by mohithg** [comment]
@dusterio Did you do `npm install` again to get the new changes

**Comment by jamesperi** [comment]
In the version 1.1 pulled via NPM, line 117 of build/index.js has
`
label: _react2.default.PropTypes.label
`

Which doesn't match the whats in the repo..

regards!

**Comment by mohithg** [comment]
@jamesperi Thanks for reaching out. I have updated the new version 1.1.1, please pull the latest via NPM.
Thanks
