### ISSUE TITLE
Deprecation warning in React v15

### ISSUE THREAD

**Issue by derwaldgeist** [mohithg/react-switchery#6]
If I am using this switch in React v15, I get this deprecation warning

> Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs

**Comment by mohithg** [comment]
@derwaldgeist Thanks for using react-switchery. Fixed the issue in 1.1.4.
