### ISSUE TITLE
onClick event not working.

### ISSUE THREAD

**Issue by carlos-max** [mohithg/react-switchery#8]
The onClick event is not working on the input. 
I fixed it by moving the handler to the div.

![image](https://user-images.githubusercontent.com/16707756/30698137-69b29848-9eb7-11e7-8ba1-dd1c5a41a137.png)

**Comment by mohithg** [comment]
@carlos-max thanks for your suggestion. Can you raise a pull request for the same. I can integrate your change into the repo

**Comment by mohithg** [comment]
Fixed in #1.1.5
